services:
  - type: web
    name: llm-efficiency-backend
    env: python
    rootDir: Backend/production

    buildCommand: pip install -r requirements-cloud.txt
    startCommand: gunicorn --workers 1 --threads 4 --bind 0.0.0.0:$PORT cloud_api:app
    healthCheckPath: /api/health

    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
