services:
  - type: web
    name: llm-efficiency-backend
    env: python
    rootDir: Backend/production

    buildCommand: pip install -r requirements-cloud.txt
    startCommand: python cloud_api.py
    healthCheckPath: /api/health

    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
